<?php echo $this->render('/navigation/adminNav.phtml'); ?>
<html lang="en"><head>
    <meta charset="utf-8">
    <title>Edge - Modern Bootstrap Template</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/font-awesome.css">
    <link rel="stylesheet" href="css/theme.css">
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Patua+One">
    <!--[if lt IE 9]>
      <link rel="stylesheet" href="css/font-awesome-ie7.css">
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="favicon.ico">
  </head>

  <body>
    <!-- Showcase -->
    <div class="showcase">
      <div class="container">
        <div class="row">
          <div class="span12">
            <header class="js-animated" style="opacity: 1;">
              <img src="assets/badge.png" alt="">
              <h1>New Sofistication Edges</h1>
              <p class="description">- Modernity is the foundation of our future -</p>
            </header>
          </div>
        </div>
      </div>
    </div>

    <!-- Call to Action Strip -->
    <section class="strip">
      <div class="container">
        <div class="row">
          <div class="span12">
            <h3>You better be ready to say goodbye to content chaos <a class="btn" href="#">Learn More <i class="icon icon-caret-right"></i></a></h3>
          </div>
        </div>
      </div>
    </section>

    <!-- Page Container -->
    <div class="container">

      <!-- Features Grid-->
      <div class="row">
        <div class="span3">
          <h4><i class="icon icon-beaker"></i> Latest technologies</h4>
          <p>Well it’s taken a lot of effort, and I’ve learnt a fair bit <a href="#" rel="tooltip" data-original-title="Right away!">on the way</a>, but my blog is finally live! It’ll have all the useful things I make.</p>
        </div>
        <div class="span3">
          <h4><i class="icon icon-credit-card"></i> Built-in E-commerce</h4>
          <p>Over the past few weeks I’ve been playing around with using display: inline-block instead of float: left to create things like horizontal lists.</p>
        </div>
        <div class="span3">
          <h4><i class="icon icon-truck"></i> Free fast delivery</h4>
          <p>Grown a lot in the last 3 years, with offices opening around the world and a quickly growing team of passionate creators, we are reinventing.</p>
        </div>
        <div class="span3">
          <h4><i class="icon icon-globe"></i> World Wide Web</h4>
          <p>This September we are re-launching Playground with a vision to change the way our industry thinks and works, sparking the next great revolution.</p>
        </div>
      </div>

      <hr>

      <!-- Info Row 1 -->
      <div class="row">
        <div class="span3">
          <img class="img-rounded" src="assets/product-4.png" alt="">
        </div>
        <div class="span9">
          <h3>Brand New Features</h3>
          <p>Easy to learn. Flexible to use. Create truly modern product support with visually-engaging guides that are available to anyone on any device. Connect your community through project documentation. Allow everyone to help out while recognizing the most valuable contributors. Improve employee training with <a href="#" rel="tooltip" data-original-title="HTML5 &amp; CSS3">cutting-edge</a> work instructions that improve production quality while reducing human errors and cycle times.</p>
          <p>Create truly modern product support with visually-engaging guides that are available to anyone on any device. Connect your community through project documentation. Allow everyone to help out while recognizing the most valuable contributors. Improve employee training with cutting-edge work instructions that improve production quality while reducing human errors and cycle times.</p>
          <a href="#" class="btn">Learn More</a>
        </div>
      </div>

      <hr>

      <!-- Info Row 2 -->
      <div class="row">
        <div class="span4">
          <h3>Feature Rich Interface</h3>
          <p>Guidebook is opinionated. We believe that how-to instructions should be broken into steps. Textual instructions alone aren't good enough—each step must also have photos in a consistent aspect ratio (4:3, the native aspect ratio of consumer digital cameras). People work best when they're given a framework that inspires creativity.</p>
          <a href="#" class="btn">View Interface</a>
        </div>
        <div class="span4">
          <h3>Fully Customizable</h3>
          <p>Wikis are useful. Unfortunately, most wikis are difficult to use and harder to organize. Unstructured documentation leads to organizational chaos and inconsistent formatting. Guidebook's elegant presentation makes your content look good from day one. Consistent layouts present instructions clearly—<a href="#" rel="tooltip" data-original-title="We mean it">on every page</a>.</p>
          <a href="#" class="btn">Try The Demo</a>
        </div>
        <div class="span4">
          <img class="img-rounded" src="assets/product-3.png" alt="">
        </div>
      </div>

      <hr>

      <!-- Testimonials -->
      <div class="row">
        <!-- Testimony 1 -->
        <div class="span4">
          <h3>Excelent Service</h3>
          <div class="bubble">
            <p><i class="icon-comments-alt"></i> For every dollar my company invests to increase usability, I receives $10-$100 in benefits</p>
          </div>
          <img class="user-avatar" src="assets/user-1.png" alt="">
          <blockquote>
            <p>Cooper Black</p>
            <small>Chief CEO in <cite title="Source Title">Venture Corp.</cite></small>
          </blockquote>
        </div>
        <!-- Testimony 2 -->
        <div class="span4">
          <h3>Priority Support</h3>
          <div class="bubble">
            <p><i class="icon-comments-alt"></i> Testing one user early in the project is better than testing 50 near the end.</p>
          </div>
          <img class="user-avatar" src="assets/user-2.png" alt="">
          <blockquote>
            <p>Calisto MT</p>
            <small>President in <cite title="Source Title">Asturias Inc.</cite></small>
          </blockquote>
        </div>
        <!-- Testimony 3 -->
        <div class="span4">
          <h3>First Class Work</h3>
          <div class="bubble">
            <p><i class="icon-comments-alt"></i> The difference between zero and even a little bit of data is astounding.</p>
          </div>
          <img class="user-avatar" src="assets/user-3.png" alt="">
          <blockquote>
            <p>Cambria Serif</p>
            <small>Design Manager in <cite title="Source Title">Moldova Systems</cite></small>
          </blockquote>
        </div>
      </div>

      <hr>

      <!-- Clients List -->
      <div class="row">
        <div class="span12">
          <h3>Our Awesome Clients</h3>
          <img class="customer-logo" src="assets/logo-1.png" alt="">
          <img class="customer-logo" src="assets/logo-2.png" alt="">
          <img class="customer-logo" src="assets/logo-3.png" alt="">
          <img class="customer-logo" src="assets/logo-11.png" alt="">
          <img class="customer-logo" src="assets/logo-12.png" alt="">
          <img class="customer-logo" src="assets/logo-6.png" alt="">
          <img class="customer-logo" src="assets/logo-7.png" alt="">
          <img class="customer-logo" src="assets/logo-8.png" alt="">
          <img class="customer-logo" src="assets/logo-9.png" alt="">
          <img class="customer-logo" src="assets/logo-10.png" alt="">
        </div>
      </div>

      <hr>

      <!-- Pricing -->
      <div class="row">
        <div class="span12">
          <h3>Simple Pricing</h3>
        </div>
      </div>

      <div class="row">
        <!-- Pricing Box 1 -->
        <div class="span3">
          <div class="pricing">
            <h4>$0 Simply Free <i class="icon icon-star muted pull-right"></i></h4>
            <hr>
            <ul>
              <li>For small groups</li>
              <li>3 Shared Projects</li>
              <li>1 Team Member</li>
              <li>Unlimited Storage</li>
              <li>Email Support</li>
            </ul>
          </div>
        </div>
        <!-- Pricing Box 2 -->
        <div class="span3">
          <div class="pricing">
            <h4>$9 One Time <i class="icon icon-star muted pull-right"></i><i class="icon icon-star muted pull-right"></i></h4>
            <hr>
            <ul>
              <li>Pay as you go</li>
              <li>10 Shared Projects</li>
              <li>4 Team Members</li>
              <li>Unlimited Storage</li>
              <li>Plus Phone Support</li>
            </ul>
          </div>
        </div>
        <!-- Pricing Box 3 -->
        <div class="span3">
          <div class="pricing">
            <h4>$90 Monthly <i class="icon icon-star muted pull-right"></i><i class="icon icon-star muted pull-right"></i><i class="icon icon-star muted pull-right"></i></h4>
            <hr>
            <ul>
              <li>Full features</li>
              <li>30 Shared Projects</li>
              <li>8 Team Members</li>
              <li>Unlimited Storage</li>
              <li>Plus Phone Support</li>
            </ul>
          </div>
        </div>
        <!-- Info Box -->
        <div class="span3">
          <div class="info-panel">
            <h4><i class="icon icon-info-sign"></i> Need a special pack?</h4>
            <p>If your company's needs are larger than any of our plans, let's talk. Get in touch with our support team and we will get something arranged for you.</p>
          </div>
        </div>
      </div><!-- /.row -->

      <hr>

      <!-- Contact Area -->
      <div class="row">
        <!-- Advice Banner -->
        <div class="span6">
          <img class="img-advice" src="assets/advice.png" alt="">
        </div>
        <!-- Contact Form -->
        <div class="span6">
          <h4><i class="icon icon-envelope-alt"></i> Let's get in touch now!</h4>
          <form class="form">
            <input class="span3" type="text" id="userName" placeholder="Name">
            <input class="span3" type="text" id="userEmail" placeholder="Email">
            <textarea rows="7" class="span6" id="message" placeholder="Message"></textarea>
            <button type="submit" class="btn btn-block">SUBMIT NOW!</button>
          </form>
        </div><!-- /.span6 -->
      </div><!-- /.row -->

      <hr>

    </div><!-- page /.container -->

    <footer>
      <div class="container">
        <div class="row">
          <div class="span12">
            <p class="pull-right"><a href="#">Back to top</a></p>
            <p>© 2013 Designed by <a href="http://twitter.com/heyallanmoreno">@heyallanmoreno</a></p>
          </div>
        </div>
      </div>
    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/jquery-1.8.2.min.js"><\/script>')</script>
    <script src="js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function(){
        // fancy animation - fade out header content on page scroll
        $(window).scroll(function() {
          if ($(this).scrollTop() > 10) {
            $('.js-animated').stop().animate({opacity: 0}, 200);
          }
          if ($(this).scrollTop() < 10) {
            $('.js-animated').stop().animate({opacity: 1}, 500);
          }
        });
        //bootstrap tooltip trigger
        $('[rel="tooltip"]').tooltip();
      });
    </script>
  

</body></html>