<?php echo $this->render('/navigation/adminNav.phtml'); ?>
<div class="hero-unit">    
    <h3 class="text-success">SEO Reporting Tool</h3>
    <p>
        SEO is a technique which helps search engines find and rank your site higher than the millions of other sites in response to a search query.
    </p>
    <ul>
        <li>Designed to offer you transparency and control</li>
        <li>Summarizes the data associated with each project you work when signed in to your account</li>
        <li>Provides links to control your personal settings</li>
        <li>Search engine optimization (SEO) is the process of affecting the visibility of a website or a web page in a search engine's "natural" or un-paid ("organic") search results.</li>
    </ul>
    <p><b>Security Note:</b> To maintain your safety and privacy we may sometimes ask you to verify your password even if you are already signed in. This may happen more frequently for services involving your personal information.</p>
</div>
