<div class="container" >
    
    <form method="post" class="form-signin">
        <h3 class="form-signin-heading">Please Sign-in</h3>  
        <?php
        echo $this->form->getElement('name');
        echo $this->form->getElement('pass');
        echo $this->form->getElement('submit');
        ?><br>Forgot Password ?
        <br>No problem,<a href="<?php echo $this->baseUrl(); ?>/index/recover"> click here </a>to get a new password.
    </form>
</div>