<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#"><strong>SEO</strong>Reports</a>
            <div class="nav-collapse collapse">
                <ul class="nav"><li><a href="<?php echo $this->baseUrl(); ?>/client/index">Home</a></li></ul>
                <ul class="nav"><li><a href="<?php echo $this->baseUrl(); ?>/client/report">Report</a></li></ul>
                <ul class="nav"><li><a href="<?php echo $this->baseUrl(); ?>/client/task">Task</a></li></ul>
                <ul class="nav"><li><a href="<?php echo $this->baseUrl(); ?>/client/project">Project</a></li></ul>
                <ul class="nav" style="float:right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Logged in as <strong><u style=" text-transform:capitalize;"><?php
                                    $auth = Zend_Auth::getInstance();
                                    $name = $auth->getIdentity()->name;
                                    $email = $auth->getIdentity()->email;
                                    echo $name;
                                    ?></u></strong><b class="caret"></b></a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="#myModal" data-toggle="modal"><?php print("<strong style='text-transform:capitalize;'>" . $name . "</strong><br>" . $email); ?></a></li>
                            <li class="divider"></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/index/logout">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal hide">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">×</a>

    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
        <a href="#" class="btn" onclick="closeDialog();">Cancel</a>
    </div>
</div>
<script language="JavaScript" type="text/javascript">
            function closeDialog() {
                $('#myModal').modal('hide');
            }
            ;
</script>