<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="#">SEO reports</a>
            <div class="nav-collapse">
                <ul class="nav pull-right">
                    <li class="divider-vertical"></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/index"><i class="icon-home"></i>&nbsp;&nbsp;Return to Dashboard</a></li>
                    <li class="divider-vertical"></li>
                </ul>
            </div>
        </div>
    </div>
</div>