<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="#"><strong>SEO</strong>Reports</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li><a href="<?php echo $this->baseUrl(); ?>/admin/index" >Home</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Project<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->baseUrl(); ?>/project/edit">Add Project</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/project/index">View Project</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">User<b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?php echo $this->baseUrl(); ?>/admin/edit">Add User</a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/admin/view">View User</a></li>
                        </ul>
                    </li>                  
                    <li><a href="<?php echo $this->baseUrl(); ?>/admin/report" >Reports</a></li>
                </ul>
                <ul class="nav pull-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Logged in as <strong><u style=" text-transform:capitalize;"><?php
                                    $name = Zend_Auth::getInstance()->getIdentity()->name;
                                    $email = Zend_Auth::getInstance()->getIdentity()->email;
                                    echo $name;
                                    ?></u></strong></a>
                        <ul class="dropdown-menu pull-right">

                            <li> 
                                <a href="#myModal" data-toggle="modal">
                                    <?php print("<strong style='text-transform:capitalize;'>" . $name . "</strong><br>" . $email); ?>
                                </a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/admin/forgot">Change Password !</a></li>
                            <li class="divider"></li>
                            <li class="btn btn-link pull-right"><a href="<?php echo $this->baseUrl(); ?>/index/logout">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal hide">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal">×</a>

    </div>
    <div class="modal-body">

    </div>
    <div class="modal-footer">
        <a href="#" class="btn" onclick="closeDialog();">Cancel</a>
    </div>
</div>
<script language="JavaScript" type="text/javascript">
            function closeDialog() {
                $('#myModal').modal('hide');
            }
            ;
</script>