<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">SEO Reports</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li><a href="<?php echo $this->baseurl(); ?>/project/edit">New Project</a></li>
                    <li class="active"><a href="<?php echo $this->baseurl(); ?>/admin/">User</a></li>
                    <li><a href="<?php echo $this->baseurl(); ?>/project/Keyword" >Keyword</a></li>
                    <li><a href="<?php echo $this->baseurl(); ?>/project/report" >Report</a></li>
                </ul>
                <ul class="nav" style="float: right">
                    <li><a href="<?php echo $this->baseurl(); ?>/index/index">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>