<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#"><strong>SEO</strong>Reports</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->baseUrl(); ?>/team/index">Home</a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/team/profile">Profile</a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/team/project">Manage Projects</a></li>
                </ul>
                <ul class="nav" style="float:right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">Logged in as <strong><u style=" text-transform:capitalize;"><?php
                                    $name = Zend_Auth::getInstance()->getIdentity()->name;
                                    $email = Zend_Auth::getInstance()->getIdentity()->email;
                                    $logo = Zend_Auth::getInstance()->getIdentity()->logo;
                                    $address = Zend_Auth::getInstance()->getIdentity()->address;
                                    $contact = Zend_Auth::getInstance()->getIdentity()->contact;
                                    echo $name;
                                    ?></u></strong><b class="caret"></b></a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="#myModal" data-toggle="modal"><?php print("<strong style='text-transform:capitalize;'>" . $name . "</strong><br>"); ?></a></li>
                            <li><a href="<?php echo $this->baseUrl(); ?>/team/profile">Setting</a></li>
                            <li class="divider"></li>
                            <li class="btn btn-link pull-right"><a href="<?php echo $this->baseUrl(); ?>/index/logout">Logout</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div id="myModal" class="modal hide">
    <div class="modal-header">
        <a href="#" class="close" data-dismiss="modal"><i class="icon-remove"></i></a>

    </div>
    <div class="modal-body">
        <span class="avatar hidden-phone">
            <img class="avatar" style="float: left;" src="<?php echo $this->baseUrl(); ?>/public/uploads/<?php echo $logo; ?>">
            <span class="span soften" style='text-transform:capitalize;'>Name : <?php print("$name"); ?></span><br><br>
            <span class="span soften">Email : <?php print("$email"); ?></span><br><br>
            <span class="span soften">Address : <?php print("$address"); ?></span><br><br>
            <span class="span soften">Contact : <?php print("$contact"); ?></span><br><br>
        </span>
    </div>
</div>
<script language="JavaScript" type="text/javascript">
    function closeDialog() {
        $('#myModal').modal('hide');
    }
    ;
</script>