<?php echo $this->render('navigation/teamNav.phtml') ?>
<div class="container-fluid" style='padding-top: 20px;padding-bottom: 20px;'>
        <h2>Add Task</h2>
        <hr style="border-color: #ccc;"/>
        <div class="row-fluid">
            <?php
            echo $this->form;
            ?>
        </div>
        <hr>
        <footer>
            <p>© Company 2013</p>
        </footer>
    </div>
</div>