<?php echo $this->render('navigation/teamNav.phtml') ?>
<div style="margin-top: 10px;">
    <form class="form-signin" method="post">
        <h3>Change Password</h3>
        <?php echo $this->form->getElement('code'); ?>
        <?php echo $this->form->getElement('confirmpass'); ?>
        <?php echo $this->form->getElement('pass'); ?>
        <?php echo $this->form->getElement('submit'); ?>
    </form>
</div>