<?php echo $this->render('navigation/teamNav.phtml') ?>
<div class="container-fluid" style='padding-top: 20px;padding-bottom: 20px;'>
    <div style="margin-top: 10px;" class="row-fluid">
        <h3>Change Password</h3>
        <form class="bs-docs-example" method="post" style="float: left;">
            <?php echo $this->form->getElement('code'); ?>
            <?php echo $this->form->getElement('confirmpass'); ?>
            <?php echo $this->form->getElement('pass'); ?>
            <?php echo $this->form->getElement('submit'); ?>
        </form>
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>
