<?php echo $this->render('navigation/teamNav.phtml') ?>
<div class="container-fluid" style="padding-right: 20px;padding-left: 20px;margin-top: 20px">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">My Profile</li>
                    <li><a href="<?php echo $this->baseurl(); ?>/team/profile"><i class="icon-edit"></i>Edit Profile</a></li>
                    <li><a href="<?php echo $this->baseurl(); ?>/team/forgot"><i class="icon-lock"></i>Change Password</a></li>
                    <li class="nav-header">Project</li>
                    <li><a href="<?php echo $this->baseurl(); ?>/team/project"><i class="icon-tasks"></i>Projects</a></li>
                    <li class="nav-header">Task & Report</li>
                    <li><a href="<?php echo $this->baseurl(); ?>/team/edit"><i class="icon-plus"></i>Add task</a></li>
                    <li><a href="<?php echo $this->baseurl(); ?>/team/team"><i class="icon-share"></i>View task(s)</a></li>
                </ul>
            </div>
        </div>
        <div class="span9">
            <div class="hero-unit">
                <h1>Team Section!</h1>
                <h3 style="text-transform: capitalize;">Welcome <?php
                    $auth = Zend_Auth::getInstance();
                    $name = $auth->getIdentity()->name;
                    echo $name;
                    ?></h3>
            </div>
        </div>
    </div>
</div>