<?php echo $this->render('navigation/teamNav.phtml') ?>
<?php
$auth = Zend_Auth::getInstance();
$name = $auth->getIdentity()->name;
$logo = $auth->getIdentity()->logo;
?>
<div class="container" style="padding-right: 20px;padding-left: 20px;margin-top: 20px">
    <div class="row-fluid">
        <div class="heading">
            <h1>Team Section!</h1>
            <h3 style="text-transform: capitalize;">Welcome <?php echo $name; ?></h3>
        </div>
    </div>
    <div class="row-fluid" style="height:500px;">
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>
