<?php echo $this->render('navigation/teamNav.phtml'); ?>
<div class="container" style='padding-top: 20px;padding-bottom: 20px;margin-top: 20px;'>
    <div class="row-fluid">
        <h2>Edit Profile</h2>
        <hr style="border-color: #ccc;"/>
        <div class="bs-docs-example">    
            <?php echo $this->form; ?>
        </div>
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>