<?php echo $this->render('/navigation/teamNav.phtml'); ?>
<div class="container" style='padding-top: 20px;padding-bottom: 20px;'>
    <h2>Project & task</h2>
    <hr style="border-color: #ccc;"/>
    <div class="row-fluid"> 
        <?php if (isset($this->row)) {
            ?>
            <table class="table table-bordered">
                <thead><tr><th>Project Title</th><th>Description</th><th>Date Added</th><th>Settings</th></tr></thead>               
                <?php
                foreach ($this->row as $v) {
                    ?>
                    <tr id="tool">
                        <td><a href="<?php echo $this->baseUrl() . "/project/view/id/" . $v['id']; ?>"><?php echo $v->title; ?></a>
                        </td><td><?php echo $v->description; ?></td>
                        <td><?php echo $v->date_added ?></td><td>
                            <a class="btn btn-success" href="<?php echo $this->baseUrl(); ?>/team/edit/id/<?php echo $v['id']; ?>" data-toggle="tooltip"  title="New Task" ><i class="icon-plus icon-white"></i></a>
                            <a class="btn btn-warning" data-toggle="tooltip"  title="Update Info" href="<?php echo $this->BaseUrl(); ?>/team/updt/id/<?php echo $v['id']; ?>" ><i class="icon-cog icon-white"></i></a>
                            <a class="btn btn-info" href="<?php echo $this->baseUrl(); ?>/team/report/id/<?php echo $v['id']; ?>" data-toggle="tooltip"  title="Manage Task(s)" ><i class="icon-tasks icon-white"></i></a>
                        </td>
                    </tr>
                    <?php
                }
            }
            ?>    
        </table>  
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>
<script language="JavaScript" type="text/javascript">
    $("#tool a[href]").tooltip();
</script>