<?php echo $this->render('/navigation/teamNav.phtml') ?>
<div class="container" style="padding-right: 20px;padding-left: 20px;margin-top: 20px">
    <div class="hero-unit">
        <h2>View Reports</h2>
    </div>
    <?php
    if (isset($this->show)) {
        ?>
        <table class="table table-bordered">
            <thead><tr><th>Name</th><th>Description</th><th>File</th></tr></thead>   
            <?php
            foreach ($this->show as $v) {
                ?>
                <tbody>
                    <tr>
                        <td><?php echo $v['title']; ?></td>
                        <td><?php echo $v['description']; ?></td>
                        <td><a href="<?php echo $this->BaseUrl(); ?>/public/uploads/<?php echo $v['attachment']; ?>" target="blank"><i class="icon-file"></i></a></td>
                    </tr>
                </tbody>

                <?php
            }
        }
        ?>
    </table>
</div>