<?php echo $this->render('/navigation/teamNav.phtml') ?>
<div class="container" style="padding-right: 20px;padding-left: 20px;margin-top: 20px">
    <div class="row-fluid">
        <h2>View Reports</h2>

        <?php
        //  if (isset($this->show)) {
        ?>
        <table class="table table-bordered">
            <thead><tr><th>Name</th><th>Description</th><th>File</th></tr></thead>   
            <?php
            foreach ($this->row as $v) {
                ?>
                <tbody>
                    <tr id="tool">
                        <td><?php echo $v['title']; ?></td>
                        <td><?php echo $v['description']; ?></td>
                        <td>
                            <a class="btn btn-warning" data-toggle="tooltip"  title="Update Info" href="<?php echo $this->BaseUrl(); ?>/team/updt/id/<?php echo $v['id']; ?>" ><i class="icon-cog icon-white"></i></a>
                            <a class="btn btn-info" data-toggle="tooltip"  title="Attachment" href="<?php echo $this->BaseUrl(); ?>/public/uploads/<?php echo $v['attachment']; ?>" target="blank"><i class="icon-file icon-white"></i></a>
                        </td>
                    </tr>
                </tbody>
                <?php
            }
            //   }
            ?>
        </table>
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>
<script language="JavaScript" type="text/javascript">
    $("#tool a[href]").tooltip();
</script>