
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">Team Section</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="<?php echo $this->baseurl(); ?>/team/edit/">Add Member</a></li>
                    <li><a href="<?php echo $this->baseurl(); ?>/team/forgot/">Change Password</a></li>
                    <li><a href="<?php echo $this->baseurl(); ?>/team/">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php
if (isset($this->data)) {
    ?>
    <table style="width: 75%;margin-top: 50px;" class="table table-bordered" align="center">

        <thead><tr><th>ID</th><th>Name</th><th>Email</th><th>File</th><th>Settings</th></tr></thead>   
        <?php
        foreach ($this->data as $v) {
            ?>
            <tbody>
                <tr>
                    <td><?php echo $v->id ?></td><td><?php echo $v->name ?></td><td><?php echo $v->email ?></td>
                    <td><a href="<?php echo $this->baseurl(); ?>/public/uploads/<?php echo $v['file']?>"><i class="icon-file"></i></a></td>
                    <td><a href="<?php echo $this->baseurl(); ?>/team/updt/id/<?php echo $v['id'] ?>"><i class="icon-cog"></i></a>|
                        <a href="<?php echo $this->baseurl(); ?>/team/del/id/<?php echo $v['id'] ?>"><i class="icon-trash"></i></a>
                    </td>
                </tr>
            </tbody>

            <?php
        }
    }
    ?>    
</table>