<?php
echo $this->render('/navigation/teamNav.phtml');
?>
<div class="container-fluid" style='padding-top: 20px;padding-bottom: 20px;'>
    <div style="margin-top: 10px;" class="row-fluid">
        <?php
        if (isset($this->show)) {
            ?>
            <table class="table table-bordered">
                <thead><tr><th>Title</th><th>Time Added</th><th>Added by</th><th>Assigned to</th><th>File</th></tr></thead>   
                <?php
                foreach ($this->show as $v) {
                    ?>
                    <tbody>
                        <tr>

                            <td><?php echo $v['title'] ?></td>
                            <td><?php echo $v['time_added'] ?></td>
                            <td><?php echo $v['added_by'] ?></td>
                            <td><?php echo $v['assign_to'] ?></td>
                            <td><a href="<?php echo $this->baseUrl(); ?>/public/uploads/<?php echo $v['attachment'] ?>" target="blank"><i class="icon-file"></i></a></td>
                        </tr>
                        <!--</tbody>-->

                        <?php
                    }
                }
                ?>    
        </table> 
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>