<?php echo $this->render('navigation/teamNav.phtml');
?>
<div class="container" style="padding-right: 20px;padding-left: 20px;margin-top: 20px">
    <div class="row-fluid">
        <div class="heading">
            <h2>Update Task</h2>
        </div>
        <div class="row-fluid">    
            <div class="bs-docs-example">
                <?php echo $this->form; ?>
            </div>
        </div>
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>
