<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Test</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <!-- CSS Style Sheets -->

        <link href="<?php echo $this->BaseUrl(); ?>/Bootstrap/css/bootstrap.css" rel="stylesheet" type="text/css" media="screen">
        <link href="<?php echo $this->BaseUrl(); ?>/Bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="screen">
        <link href="<?php echo $this->BaseUrl(); ?>/Bootstrap/css/bootstrap-responsive.css" rel="stylesheet" type="text/css" media="screen">
        <link href="<?php echo $this->BaseUrl(); ?>/Bootstrap/css/bootstrap-responsive.min.css" rel="stylesheet" type="text/css" media="screen">
        <link href="<?php echo $this->BaseUrl(); ?>/Bootstrap/css/ui.daterangepicker.css" rel="stylesheet" type="text/css" media="screen">
        <link href="<?php echo $this->BaseUrl(); ?>/Bootstrap/css/jquery-ui.css" rel="stylesheet" type="text/css" media="screen">
        <link href="<?php echo $this->BaseUrl(); ?>/Bootstrap/css/jquery-ui-timepicker-addon.css" rel="stylesheet" type="text/css" media="screen">
        <!-- Icon Files -->
        <link rel="icon" href="<?php echo $this->BaseUrl(); ?>/Bootstrap/img/glyphicons-halflings-white.png" type="image/x-icon"/>
        <link rel="icon" href="<?php echo $this->BaseUrl(); ?>/Bootstrap/img/glyphicons-halflings.png" type="image/x-icon"/>
        <link rel="shortcut icon" href="<?php echo $this->BaseUrl(); ?>/Bootstrap/images/ui.png"  type="image/x-icon" />
        <!-- JavaScript Files  -->
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/jquery.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/jquery-ui.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap.min.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/jquery-ui-timepicker-addon.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/jquery-ui-sliderAccess.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/date.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/daterangepicker.jQuery.compressed.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/daterangepicker.jQuery.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-button.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-carousel.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-dropdown.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-popover.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-scrollspy.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootbox.min.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-tab.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-typehead.js"></script>   
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-alert.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-tab.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-modal.js"></script>
        <script src="<?php echo $this->BaseUrl(); ?>/Bootstrap/js/bootstrap-collapse.js"></script>
        <!-- Datetime Picker  -->
        <script>
            $(function() {
                $(".datetimepicker").datetimepicker({dateFormat: 'yy-mm-dd'});
            });
        </script>
        <!-- Date Picker  -->
        <script>
            $(function() {
                $(".datepicker").datepicker({dateFormat: 'yy-mm-dd'});
            });
        </script>
        <!-- Date Range Picker  -->
        <script type="text/javascript">
            $(function() {
                $('.daterangepicker').daterangepicker({dateFormat: 'yy-mm-dd'});
            });
        </script>
        <style type="text/css">
            body {
                padding-top: 40px;
                padding-bottom: 40px;
                background-color: white;
            }

            .form-signin {
                max-width: 300px;
                padding: 19px 29px 29px;
                margin: 0 auto 20px;
                background-color: #fff;
                border: 1px solid #e5e5e5;
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
                -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
            }
            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }
            .form-signin input[type="text"],
            .form-signin input[type="password"] {
                font-size: 16px;
                height: auto;
                margin-bottom: 15px;
                padding: 7px 9px;
            }
            .form-signin input[type="submit"]{
                icon: url('glyphicons-halflings-white.png');
            }
        </style>
    </head>
    <body>
        <?php echo $this->layout()->content; ?>
    </body>
</html>