<?php echo $this->render('navigation/clientNav.phtml'); ?>
<div class="container" style="padding-right: 20px;padding-left: 20px;margin-top: 20px">
    <div class="row-fluid">
        <div class="heading">
            <h1>Client Section!</h1>
            <h3>Welcome <?php
                $auth = Zend_Auth::getInstance();
                $name = $auth->getIdentity()->name;
                echo "<span style='text-transform: capitalize;'>" . $name . "</span>";
                ?></h3>    
            <hr style="border-color: #ccc;"/>
        </div>
    </div>
    <div class="row-fluid" style="height:500px;">

    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>