<?php
echo $this->render('/navigation/clientNav.phtml');
?>    
<div class="container" style="margin-top: 20px;">
    <div class="row-fluid">
        <div class="hero-unit">
            <h2>Project Section</h2>
        </div>
        <div class="row-fluid">
            <?php
            if (isset($this->show)) {
                ?>
                <table class="table table-bordered">
                    <thead><tr><th>Project Title</th><th>Description</th><th>Date Added</th><th>file</th></tr></thead>       
                    <tbody>
                        <?php
                        foreach ($this->show as $v) {
                            ?>
                            <tr>
                                <td><?php echo $v['title'] ?></td>
                                <td><?php echo $v['description'] ?></td>
                                <td><?php echo $v['date_added'] ?></td>
                                <td><a href="<?php echo $this->baseurl(); ?>/public/uploads/<?php echo $v['attachment'] ?>" target="blank"><i class="icon-file"></i></a></td>
                            </tr>
                            <?php
                        }
                    }
                    ?>   
                </tbody>
            </table>
        </div>
    </div>
    <hr>

    <footer>
        <div id="footer">
            <div class="container">
                <p class="muted credit">Example courtesy <a href="http://twitter.github.com/bootstrap/">Bootstrap</a> and <a href="https://www.facebook.com/odit.verma">Odit Verma</a>.</p>
            </div>
        </div>
    </footer>
</div>