<?php
echo $this->render('/navigation/clientNav.phtml');
if (isset($this->show)) {
    foreach ($this->show as $v) {
        ?>    
      
<div class="container">
      <div class="container-narrow" style="float: top">
            <div class="masthead">
                <h3 style="text-transform: capitalize;"><?php echo $v['title']; ?></h3>
                <hr>
            </div>
        </div>
    <?php
    }
}
?>
    <div class="row">
        <div class="span4" style="width:45%;">
            <h2>View Task</h2>
            View the tasks ,check their status either it is active or De-active. 
            <p></p>
            <p><a class="btn" href="<?php echo $this->baseurl(); ?>/client/task">View Reports »</a></p>
        </div>
        <div class="span4">
            <h2>Reports</h2>
            <p>It consists of analysis of the website with respect to the on-site, on-page, off-page factors, proposed list of keywords, proposed changes, proposed plan of action, SEO pricing and features.</p>
            <p><a class="btn" href="<?php echo $this->baseurl(); ?>/client/report">View Reports »</a></p>
        </div>

    </div>

    <hr>

    <footer>
        <div id="footer">
            <div class="container">
                <p class="muted credit">Example courtesy <a href="http://twitter.github.com/bootstrap/">Bootstrap</a> and <a href="https://www.facebook.com/odit.verma">Odit Verma</a>.</p>
            </div>
        </div>
    </footer>
</div>