<?php echo $this->render('/navigation/clientNav.phtml');?>
<?php
echo $this->form;
if (isset($this->show)) {
    ?>

    <table style="width:50%;" class="table table-bordered">
        <thead><tr><th>Name</th><th>Description</th><th>File</th></tr></thead>   
        <?php
        foreach ($this->show as $v) {
            ?>
            <tbody>
                <tr>
                    <td><?php echo $v['task'] ?></td>
                    <td><?php echo $v['description'] ?></td>
                    <td><a href="<?php echo $this->baseurl(); ?>/public/uploads/<?php echo $v['attachment'] ?>" target="blank"><i class="icon-file"></i></a></td>
                </tr>
            </tbody>

            <?php
        }
    }
    ?>
</table>
