<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">SEO Reports</a>
            <div class="nav-collapse collapse">
                <ul class="nav" style="float: right">
                    <li><a href="<?php echo $this->baseurl(); ?>/client/index">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
<?php
echo $this->form;
if (isset($this->show)) {
    ?>

    <table style="width:auto;" class="table table-bordered">
        <thead><tr><th>Name</th><th>Description</th><th>File</th></tr></thead>   
        <?php
        foreach ($this->show as $v) {
            ?>
            <tbody>
                <tr>
                    <td><?php echo $v['title'] ?></td>
                    <td><?php echo $v['description'] ?></td>
                    <td><a href="<?php echo $this->baseurl(); ?>/public/uploads/<?php echo $v['attachment'] ?>" target="blank"><i class="icon-file"></i></a></td>
                </tr>
            </tbody>

            <?php
        }
    }
    ?>
</table>
