<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">SEO Reports</a>
            <div class="nav-collapse collapse">
                <ul class="nav" style="float: right">
                    <li><a href="<?php echo $this->baseurl(); ?>/client/index">Logout</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Main hero unit for a primary marketing message or call to action -->
<div class="container">
    <div class="hero-unit">
        <h2></h2>

    </div>

    <!-- Example row of columns -->
    <div class="row">
        <div class="span4" style="width:45%;">
            <h3>View Task</h3>
            <?php
            if (isset($this->show)) {
                ?>
                <table style="width:auto;" class="table table-bordered">
                    <thead><tr><th>Name</th><th>Description</th><th>Date added</th><th>Status</th><th>File</th></tr></thead>   
                    <?php
                    foreach ($this->show as $v) {
                        ?>
                        <tbody>
                            <tr>
                                <td><?php echo $v['title'] ?></td>
                                <td><?php echo $v['description'] ?></td>
                                <td><?php echo $v['date_added'] ?></td>
                                <td><?php
                                    if ($v['status'] == 1) {
                                        print("Active");
                                    }
                                    if ($v['status'] == 0) {
                                        print("Deactive");
                                    }
                                    ?></td>
                                <td><a href="<?php echo $this->baseurl(); ?>/public/uploads/<?php echo $v['attachment']?>"><i class="icon-file"></i></a></td>
                            </tr>
                        </tbody>

                        <?php
                    }
                }
                ?>    
            </table>   
        </div>
        <div class="span4" style="width:50%;">
            <h3>View Report</h3>

        </div>

    </div>

    <hr>

    <footer>
        <div id="footer">
            <div class="container">
                <p class="muted credit">Example courtesy <a href="#">Bootstrap</a> and <a href="#">Odit Verma</a>.</p>
            </div>
        </div>
    </footer>
</div>