<?php echo $this->render('navigation/nav.phtml'); ?>
<div class="container" style="margin-top: 20px;padding-top: 20px;padding-bottom: 20px;">
    <div class="row-fluid">
        <h2>Add Project(s)</h2>
        
            <div class="bs-docs-example">
                <?php
                echo $this->form;
                ?>
         </div>        
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>