<?php echo $this->render('navigation/nav.phtml'); ?>
<div class="container" style="margin-top: 20px;padding-top: 20px;padding-bottom: 20px;">
    <h2>Add Project(s)</h2>
    <hr style="border-color: #ccc;"/>
    <div class="bs-docs-example">
        <div class="row-fluid">    
            <div class="span4">
                <?php
                echo $this->form;
                ?>
            </div>
            <div class="span8">
            <img src="<?php echo $this->BaseUrl(); ?>/Bootstrap/img/seo.jpg">
            </div>
        </div>        
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>