<?php echo $this->render('/navigation/nav.phtml'); ?>
<div class="container" style="margin-top: 20px;">
    <div class="row-fluid">
        <div class="hero-unit">
            <h2>Project Section</h2>
        </div>

        <div class="row-fluid">
            <?php
            if (isset($this->data)) {
                ?>
                <table class="table table-bordered">
                    <thead><tr><th>Project Title</th><th>Description</th><th>Date Added</th><th>Status</th><th>File</th><th>Settings</th></tr></thead>       
                    <?php
                    foreach ($this->data as $v) {
                        ?>
                        <tbody><tr>
                                <td><?php echo $v->title ?></td><td><?php echo $v->description ?></td>
                                <td><?php echo $v->date_added ?></td><td><?php
                                    if ($v->status == 0) {
                                        echo '<span class="badge badge-important">De-active</span>';
                                    } else {
                                        echo '<span class="badge badge-success">Active</span>';
                                    }
                                    ?></td><td><a href="<?php echo $this->baseUrl(); ?>/public/uploads/<?php echo $v->attachment ?>"><i class="icon-file"></i></a></td>
                                <td>        
                                    <?php if ($v->status == 1) { ?>   <a href="<?php echo $this->baseUrl(); ?>/project/status/id/<?php echo $v['id'] ?>" class="btn btn-success" data-toggle="tooltip" title="Status Active"  ><i class="icon-ok-sign icon-white"></i></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $this->baseUrl(); ?>/project/status/id/<?php echo $v['id'] ?>" class="btn btn-danger" data-toggle="tooltip" title="Status De-active" ><i class="icon-ban-circle icon-white"></i></a>
                                    <?php } ?>                                          
                                    <a href="<?php echo $this->baseUrl(); ?>/project/keyword/id/<?php echo $v['id'] ?>" class="btn btn-inverse" data-toggle="tooltip"  title="Manage keyword" ><i class="icon-tags icon-white"></i></a>
                                    <a href="<?php echo $this->baseUrl(); ?>/project/update/id/<?php echo $v['id'] ?>" class="btn btn-info"  data-toggle="tooltip"   title="Update Project" ><i class="icon-cog icon-white"></i></a>                   
                                    <a href="<?php echo $this->baseUrl(); ?>/project/delete/id/<?php echo $v['id'] ?>" onclick="del(<?php echo $v['id'] ?>)" class="btn btn-danger" data-toggle="tooltip"   title="Delete Project"><i class='icon-trash icon-white'></i></a>
                                </td></tr>
                        </tbody>
                        <?php
                    }
                }
                ?>    
            </table>
        </div>
    </div>
</div>
<script language="JavaScript" type="text/javascript">
    $("#tool a[href]").tooltip();
</script>

<script language="JavaScript" type="text/javascript">
    function del(id) {
        if (confirm('Are you sure you want to delete it ?')) {
            window.location = "<?php echo $this->baseUrl(); ?>/project/delete/id/" + id;
        }
    }
</script>