<?php echo $this->render('/navigation/nav.phtml'); ?>
<div class="container" style="margin-top: 20px;padding-top: 20px;padding-bottom: 20px;">
    <div class="row-fluid">
        <div class="heading">
            <h2>Project Section</h2>
            <hr style="border-color: #ccc;"/>
        </div>

        <div class="row-fluid">
            <?php
            if (isset($this->data)) {
                ?>
                <table class="table table-bordered">
                    <thead><tr><th>Project Title</th><th>Description</th><th>Date Added</th><th>Status</th><th>File</th><th>Settings</th></tr></thead>       
                    <?php
                    foreach ($this->data as $v) {
                        ?>
                        <tbody><tr id="tool">
                                <td><?php echo $v->title ?></td><td><?php echo $v->description ?></td>
                                <td><?php echo $v->date_added ?></td><td><?php
                                    if ($v->status == 0) {
                                        echo '<span class="badge badge-important">De-active</span>';
                                    } else {
                                        echo '<span class="badge badge-success">Active</span>';
                                    }
                                    ?></td><td><a href="<?php echo $this->baseUrl(); ?>/public/uploads/<?php echo $v->attachment ?>"><i class="icon-file"></i></a></td>
                                <td>        
                                    <?php if ($v->status == 1) { ?>   <a href="<?php echo $this->baseUrl(); ?>/project/status/id/<?php echo $v['id'] ?>" class="btn btn-danger" data-toggle="tooltip" title="Status Active"  ><i class="icon-ban-circle icon-white"></i></a>
                                    <?php } else { ?>
                                        <a href="<?php echo $this->baseUrl(); ?>/project/status/id/<?php echo $v['id'] ?>" class="btn btn-success" data-toggle="tooltip" title="Status De-active" ><i class="icon-ok-sign icon-white"></i></a>
                                    <?php } ?>                                          
                                    <a href="<?php echo $this->baseUrl(); ?>/project/keyword/id/<?php echo $v['id'] ?>" class="btn btn-inverse" data-toggle="tooltip"  title="Manage keyword" ><i class="icon-tags icon-white"></i></a>
                                    <a href="<?php echo $this->baseUrl(); ?>/project/update/id/<?php echo $v['id'] ?>" class="btn btn-warning"  data-toggle="tooltip"   title="Update Project" ><i class="icon-cog icon-white"></i></a>                   
                                    <a href="<?php echo $this->Url(array('controller' => 'Project', 'action' => 'delete', 'id' => $v['id'])) ?>" class="btn btn-danger" data-toggle="tooltip"   title="Delete"
                                       onclick="return confirm('Do you really want to delete this?');">
                                        <i class="icon-trash icon-white" title='Delete'></i>
                                    </a>
                                </td></tr>
                        </tbody>
                        <?php
                    }
                }
                ?>    
            </table>
        </div>
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>
<script language="JavaScript" type="text/javascript">
                                   $("#tool a[href]").tooltip();
</script>