<?php echo $this->render('navigation/nav.phtml'); ?>
<div class="container">
    <h3>Keyword Allocation</h3>
    <div class="front">
        <?php
        echo $this->form;
        if (isset($this->select)) {
            ?>
        </div>
        <table  class="table table-bordered">
            <thead><tr><th>Keyword</th><th>Date Added</th><th>Priority</th><th>Settings</th></tr></thead>       
            <?php
            $pos=array();
            foreach ($this->select as $v) {
                $pos[] = $v->pos;
            }
            if(!empty($pos)){
                $maxPos = max($pos);
                $minPos = min($pos);
            }
            else{
                $maxPos='';
                $minPos='';
            }
            foreach ($this->select as $v) {
                ?>
                <tbody><tr>
                        <td><?php echo $v->keyname ?></td>
                        <td><?php echo $v->timeadded ?></td>
                        <td><?php if ($v->pos == $minPos) { ?>  
                                <a style="visibility:hidden;" href="<?php echo $this->baseUrl(); ?>/project/keyup/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class="icon-arrow-up"></i></a>|
                                <a href="<?php echo $this->baseUrl(); ?>/project/keydown/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class='icon-arrow-down'></i></a>
                            <?php } else if ($v->pos == $maxPos) {
                                ?>
                                <a  href="<?php echo $this->baseUrl(); ?>/project/keyup/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class="icon-arrow-up"></i></a>|                    
                                <a style="visibility:hidden;" href="<?php echo $this->baseUrl(); ?>/project/keydown/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class='icon-arrow-down'></i></a>
                            <?php } else {
                                ?>
                                <a  href="<?php echo $this->baseUrl(); ?>/project/keyup/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class="icon-arrow-up"></i></a>|                    
                                <a href="<?php echo $this->baseUrl(); ?>/project/keydown/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class='icon-arrow-down'></i></a>
                            <?php }
                            ?>
                        </td>
                        <td>
                            <a href="<?php echo $this->baseUrl(); ?>/project/keyupdt/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class="icon-cog"></i></a>|                    
                            <a href="<?php echo $this->baseUrl(); ?>/project/keydel/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class='icon-trash'></i></a>
                        </td></tr>
                </tbody>
                <?php
            }
        }
        ?>    
    </table>
</div>