<?php echo $this->render('navigation/nav.phtml'); ?>
<?php
$title = $this->data;
$title->toArray();
?>
<div class="container" style="margin-top: 20px;padding-top: 20px;padding-bottom: 20px;">
    <div class="row-fluid">
        <span style="font-size: 32px;">Keyword Allocation</span>
        <hr style="border-color: #ccc;"/>
        <div class="bs-docs-example">
            <div class="row-fluid">
                <div class="span4">
                    <span style="text-transform:  uppercase;font-size: 24px;">Campaign Name : <?php print_r($title[0]['title']); ?> </span>
                    <?php echo $this->form; ?>
                    <?php if (isset($this->select)) {
                        ?>
                    </div>
                    <div class="span8">
                        <p style="float:left;margin-left:1em"> 
                            <img src="<?php echo $this->baseUrl(); ?>/images/key.jpg" width="300" height="250" style="margin-top: -10px;">
                        </p>
                        <p style="font-size: 16px;"><strong>Keywords</strong> are the most important SEO element for every search engine, they are what search strings are matched against. Choosing the right keywords to optimize for is thus the first and most crucial step to a successful SEO campaign. If you fail on this very first step, the road ahead is very bumpy and most likely you will only waste your time and money. There are many ways to determine which keywords to optimize for and usually the final list of them is made after a careful analysis of what the online population is searching for, which keywords have your competitors chosen and above all - which are the keywords that you feel describe your site best.</p>

                    </div>
                </div>    
            </div>
            <table  class="table table-bordered">
                <thead><tr><th>Keyword</th><th>Date Added</th><th>Priority</th><th>Settings</th></tr></thead>       
                <?php
                $pos = array();
                foreach ($this->select as $v) {
                    $pos[] = $v->pos;
                }
                if (!empty($pos)) {
                    $maxPos = max($pos);
                    $minPos = min($pos);
                } else {
                    $maxPos = '';
                    $minPos = '';
                }
                foreach ($this->select as $v) {
                    ?>
                    <tbody><tr id="tool">
                            <td><?php echo $v->keyname ?></td>
                            <td><?php echo $v->timeadded ?></td>
                            <td><?php if ($v->pos == $minPos) { ?>  
                                    <a style="visibility:hidden;" href="<?php echo $this->baseUrl(); ?>/project/keyup/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class="icon-arrow-up"></i></a>
                                    <a href="<?php echo $this->baseUrl(); ?>/project/keydown/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class='icon-arrow-down'></i></a>
                                <?php } else if ($v->pos == $maxPos) {
                                    ?>
                                    <a  href="<?php echo $this->baseUrl(); ?>/project/keyup/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class="icon-arrow-up"></i></a>                    
                                    <a style="visibility:hidden;" href="<?php echo $this->baseUrl(); ?>/project/keydown/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class='icon-arrow-down'></i></a>
                                <?php } else {
                                    ?>
                                    <a  href="<?php echo $this->baseUrl(); ?>/project/keyup/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class="icon-arrow-up"></i></a>                  
                                    <a href="<?php echo $this->baseUrl(); ?>/project/keydown/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class='icon-arrow-down'></i></a>
                                <?php }
                                ?>
                            </td>
                            <td>
                                <a class="btn btn-warning" data-toggle="tooltip"  title="Update keyword" href="<?php echo $this->baseUrl(); ?>/project/keyupdt/projectId/<?php echo $v['project_id'] ?>/id/<?php echo $v['id'] ?>"><i class="icon-cog icon-white"></i></a>            
                                <a class="btn btn-danger" data-toggle="tooltip"  title="Delete Keyword" href="<?php echo $this->Url(array('controller' => 'Project', 'action' => 'keydel', 'id' => $v['id'])) ?>"  
                                   onclick="return confirm('Do you really want to delete this?');"><i class="icon-trash icon-white" title='Delete'></i></a>
                            </td></tr>
                    </tbody>
                    <?php
                }
            }
            ?>    
        </table>
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>
<script language="JavaScript" type="text/javascript">
                                       $("#tool a[href]").tooltip();
</script>
<script language="JavaScript" type="text/javascript">
    $("#keyname").popover();
</script>