<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="brand" href="#">SEO Reports</a>
            <div class="nav-collapse collapse">
                <ul class="nav">
                    <li class="active"><a href="#">View Task</a></li>
                    <li><a href="#about">View Reports</a></li>
                </ul>
                </ul>
            </div>
        </div>
    </div>
</div>
<h2>Update Form</h2>
    <?php
echo $this->form;
?>