<?php echo $this->render('/navigation/editNav.phtml') ?>

<form class="form-signin" method="post">
    <h3>Add New User</h3>
    <?php echo $this->form->getElement('name'); ?>
    <?php echo $this->form->getElement('pass'); ?>
    <?php echo $this->form->getElement('email'); ?>
    <?php echo $this->form->getElement('account_type'); ?>
    <?php echo $this->form->getElement('address'); ?>
    <?php echo $this->form->getElement('contact'); ?>    
    <?php echo $this->form->getElement('submit'); ?>
</form>
