<?php echo $this->render('navigation/nav.phtml') ?>
<div class="container" style='padding-top: 20px;padding-bottom: 20px;'>
    <div style="margin-top: 10px;">
        <h3 align="center">Change Password</h3>
        <form class="form-signin" method="post">
            <?php echo $this->form->getElement('code'); ?>
            <?php echo $this->form->getElement('confirmpass'); ?>
            <?php echo $this->form->getElement('pass'); ?>
            <?php echo $this->form->getElement('submit'); ?>
        </form>
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>