<?php
echo $this->render('navigation/nav.phtml');
$name = Zend_Auth::getInstance()->getIdentity()->name;
?>
<div class="container" style="margin-top: 20px;padding-top: 20px;padding-bottom: 20px;">
    <div class="row-fluid">
        <div class="heading">
            <h1>Admin Section!</h1>
            <h3 style=" text-transform:capitalize;">Welcome <?php echo $name; ?></h3>
            <hr style="border-color: #ccc;"/>
        </div>
    </div>

    <div class="row-fluid" style="height: 500px;">
    </div>

    <hr>
    <footer class="footer">
        <p>© Company 2013</p>
    </footer>
</div>