<?php echo $this->render('navigation/nav.phtml') ?>
<div class="container-fluid" style="padding-right: 20px;padding-left: 20px;margin-top: 20px">
    <div class="row-fluid">
        <div class="span3">
            <div class="well sidebar-nav">
                <ul class="nav nav-list">
                    <li class="nav-header">Project</li>
                    <li><a href="<?php echo $this->baseurl(); ?>/project/edit">Add Project</a></li>
                    <li><a href="<?php echo $this->baseurl(); ?>/project/index">View Projects</a></li>
                    <li><a href="<?php echo $this->baseurl(); ?>/project/keyword">Allocate Keywords</a></li>
                    <li class="nav-header">Reports</li>
                    <li><a href="<?php echo $this->baseurl(); ?>/admin/report">View Report</a></li>
                    <li class="nav-header">User</li>
                    <li><a href="<?php echo $this->baseurl(); ?>/admin/index">View Profile(s)</a></li>
                    <li><a href="<?php echo $this->baseurl(); ?>/admin/edit">Add User</a></li>
                    <!--<li><a href="#">Link</a></li>-->                    
                </ul>
            </div>
        </div>
        <div class="span9">
            <div class="hero-unit">
                <h1>Admin Section!</h1>
                <h3>Welcome </h3>
            </div>
            <div class="row-fluid">

                <?php
                if (isset($this->data)) {
                    ?>
                    <table class="table table-bordered" align="center">
                        <thead><tr><th>Name</th><th>Email</th><th>Account Type</th><th>Address</th><th>Status</th><th>Contact</th><th>Setting</th></tr></thead>   
                        <?php
                        foreach ($this->data as $v) {
                            ?>
                            <tbody>
                                <tr>
                                    <td><?php echo $v->name ?></td>
                                    <td><?php echo $v->email ?></td>
                                    <td><?php echo $v->account_type ?></td>
                                    <td><?php echo $v->address ?></td>
                                    <td><?php
                                        if ($v->status == 0) {
                                            echo '<u style="color: red;">De-active</u>';
                                        } else {
                                            echo '<u style="color: green;">Active</u>';
                                        }
                                        ?></td>
                                    <td><?php echo $v->contact ?></td>
                                    <td><a href="<?php echo $this->baseurl(); ?>/admin/update/id/<?php echo $v['id'] ?>"><i class="icon-cog"></i></a>|
                                        <a href="<?php echo $this->baseurl(); ?>/admin/delete/id/<?php echo $v['id'] ?>"><i class='icon-trash'></i></a>|
                                        <?php if ($v->status == 1) { ?>  <a href="<?php echo $this->baseurl(); ?>/admin/status/id/<?php echo $v['id'] ?>"><img src="<?php echo $this->baseurl(); ?>/public/Bootstrap/img/valid.png"></a><?php } else { ?>
                                            <a href="<?php echo $this->baseurl(); ?>/admin/status/id/<?php echo $v['id'] ?>"><img src="<?php echo $this->baseurl(); ?>/public/Bootstrap/img/error.png"></a> 
                                        <?php } ?>
                                    </td>
                                </tr>
                            </tbody>

                            <?php
                        }
                    }
                    ?>    
                </table>
            </div>
        </div>
    </div>
</div>