<?php
echo $this->render('navigation/nav.phtml')
?>
<?php
$auth = Zend_Auth::getInstance();
$name = $auth->getIdentity()->name;
$id=$auth->getIdentity()->id;
$logo=$auth->getIdentity()->logo;
?>
<div class="container-fluid" style="padding-right: 20px;padding-left: 20px;margin-top: 20px;">
    <div class="row-fluid">
        <div class="span3">
            <div class="member-box round-all" style="border: 1px solid #ddd;padding: 10px;background-color: #eee;">
                <a>
                    <img src="<?php echo $this->baseUrl(); ?>/public/uploads/<?php echo $logo; ?>" class="member-box-avatar" style="height: 50px;width: 50px;padding: 1px;margin-right: 10px;float: left;" />
                </a>
                <span>
                    <strong>Admin Section</strong>
                    <br>
                    <strong><span style="text-transform:capitalize;"><?php echo $name; ?></span></strong>
                    <br>
                    <span class="member-box-links">
                        <a href="<?php echo $this->baseUrl(); ?>/admin/update/id/<?php echo $id; ?>" >Settings</a>
                        |
                        <a href="<?php echo $this->baseUrl(); ?>/index/logout">Logout</a>
                    </span>
                </span>
            </div>
            <div class="well sidebar-nav"  style="margin-top: 20px;">
                <ul class="nav nav-list">
                    <li class="nav-header">Project</li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/project/edit"><i class="icon-edit"></i>Add Project</a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/project/index"><i class="icon-tasks"></i>View & Manage Projects</a></li>
                    <li class="nav-header">Reports</li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/admin/report"><i class="icon-eye-open"></i>View Report</a></li>
                    <li class="nav-header">User</li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/admin/index"><i class="icon-share"></i>View Profile(s)</a></li>
                    <li><a href="<?php echo $this->baseUrl(); ?>/admin/edit"><i class="icon-plus-sign"></i>Add User</a></li>
                    <!--<li><a href="#">Link</a></li>-->                    
                </ul>
            </div>
        </div>
        <div class="span9">
            <div class="hero-unit">
                <h1>Admin Section!</h1>
                <h3>Welcome <span style=" text-transform:capitalize;"><?php echo $name; ?></span></h3>
            </div>
            <div class="row-fluid">

                <?php
                if (isset($this->data)) {
                    ?>
                    <table class="table table-bordered">
                        <thead><tr><th>Name</th><th>Email</th><th>Account Type</th><th>Address</th><th>Status</th><th>Contact</th><th>Setting</th></tr></thead>   
                        <?php
                        foreach ($this->data as $v) {
                            ?>
                            <tbody>
                                <tr>
                                    <td><?php echo $v->name ?></td>
                                    <td><?php echo $v->email ?></td>
                                    <td><?php echo $v->account_type ?></td>
                                    <td><?php echo $v->address ?></td>
                                    <td><?php
                                        if ($v->status == 0) {
                                            echo '<span class="badge badge-important">De-active</span>';
                                        } else {
                                            echo '<span class="badge badge-success">Active</span>';
                                        }
                                        ?></td>
                                    <td><?php echo $v->contact ?></td>
                                    <td><a class="btn btn-info" href="<?php echo $this->baseUrl(); ?>/admin/update/id/<?php echo $v['id'] ?>"  data-toggle="tooltip" rel="tooltip" title="Update Info" ><i class="icon-cog icon-white"></i></a>
                                        <a class="btn btn-danger" href="<?php echo $this->baseUrl(); ?>/admin/delete/id/<?php echo $v['id'] ?>"  data-toggle="tooltip" rel="tooltip" title="Delete User" ><i class='icon-trash icon-white'></i></a>
                                        <?php if ($v->status == 1) { ?>  <a class="btn btn-success"  href="<?php echo $this->baseUrl(); ?>/admin/status/id/<?php echo $v['id'] ?>"  data-toggle="tooltip" rel="tooltip" title="Active" ><i class="icon-ok-circle icon-white"></i></a><?php } else { ?>
                                            <a class="btn btn-danger" href="<?php echo $this->baseUrl(); ?>/admin/status/id/<?php echo $v['id'] ?>"  data-toggle="tooltip" rel="tooltip" title="Unactive" ><i class="icon-ban-circle icon-white"></i>Status</a> 
                                            <?php } ?>
                                    </td>
                                </tr>
                            </tbody>

                            <?php
                        }
                    }
                    ?>    
                </table>
            </div>
        </div>
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>