<?php echo $this->render('/navigation/nav.phtml') ?>
<div class="container">
    <div class="hero-unit">
        <h2>View Reports</h2>
    </div>
    <form class="form-signin" method="post" style="float: left">
        <?php echo $this->form->getElement('pickDate'); ?>
        <?php echo $this->form->getElement('submit'); ?>
    </form>

    <?php
    if (isset($this->show)) {
        ?>
        <table class="table table-bordered">
            <thead><tr><th>Name</th><th>Description</th><th>File</th></tr></thead>   
            <?php
            foreach ($this->show as $v) {
                ?>
                <tbody>
                    <tr>
                        <td><?php echo $v['task'] ?></td>
                        <td><?php echo $v['description'] ?></td>
                        <td><a href="<?php echo $this->BaseUrl(); ?>/public/uploads/<?php echo $v['attachment'] ?>" target="blank"><i class="icon-file"></i></a></td>
                    </tr>
                </tbody>

                <?php
            }
        }
        ?>
    </table>
</div>