<?php echo $this->render('/navigation/nav.phtml') ?>
<div class="container" style='padding-top: 20px;padding-bottom: 20px;margin-top: 20px;'>
    <h3>Reports</h3>
    <hr style="border-color: #ccc;"/>
    <div class="row-fluid">

        <div class="span3">
            <?php echo $this->form; ?>
        </div>
        <div class="span9">
            <?php
            if (isset($this->show)) {
                ?>
                <table class="table table-bordered table-striped">
                    <thead><tr><th>Name</th><th>Description</th><th>File</th></tr></thead>   
                    <tbody>
                        <?php
                        foreach ($this->show as $v) {
                            ?>
                            <tr>
                                <td><?php echo $v['title']; ?></td>
                                <td><?php echo $v['description']; ?></td>
                                <td>
                                    <a href="<?php echo $this->BaseUrl(); ?>/public/uploads/<?php echo $v['attachment']; ?>" target="blank">
                                        <i class="icon-file"></i>
                                    </a>
                                </td>
                            </tr>
                            <?php
                        }
                    }
                    ?>
            <!--tr><td colspan="3"></td></tr-->
                </tbody>
            </table>
        </div>
    </div>
    <hr>
    <footer class="footer"><p>@ Company 2013</p></footer>
</div>
<!--div class="bs-docs-example">
    <ul class="pager">
        <li><a href="#">Previous</a></li>
        <li><a href="#">Next</a></li>
    </ul>
</div-->