<?php echo $this->render('navigation/nav.phtml') ?>
<div class="container-fluid" style='padding-top: 20px;padding-bottom: 20px;'>
    <div style="margin-top: 10px;" class="row-fluid">
        <h2>Update Info</h2>
        <hr style="border-color: #ccc;"/>
        <div class="bs-docs-example">
            <?php
            echo $this->form;
            ?>
        </div>
    </div>
    <hr>
    <footer>
        <p>© Company 2013</p>
    </footer>
</div>